// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWzZeNU5Gc832UzWiPIwW1_fbo6d8Cro0',
    appId: '1:469498857618:web:fc32f6d278bb6995237e4b',
    messagingSenderId: '469498857618',
    projectId: 'photogalery-2fc47',
    authDomain: 'photogalery-2fc47.firebaseapp.com',
    storageBucket: 'photogalery-2fc47.appspot.com',
    measurementId: 'G-LMFXH883W7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfJuoHOkogcehkdOu_l-xMJUaqMot1Fbo',
    appId: '1:469498857618:android:e09d8a0d3c0e987c237e4b',
    messagingSenderId: '469498857618',
    projectId: 'photogalery-2fc47',
    storageBucket: 'photogalery-2fc47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZozgUgIdPYOweBVkN1BWxcL6HWnE90kk',
    appId: '1:469498857618:ios:710b23e5f3290375237e4b',
    messagingSenderId: '469498857618',
    projectId: 'photogalery-2fc47',
    storageBucket: 'photogalery-2fc47.appspot.com',
    iosClientId: '469498857618-fdkh3144dkn3v1sv0dupelp8hupjteoj.apps.googleusercontent.com',
    iosBundleId: 'com.example.backupCamera',
  );
}
